In [ ]:
#Levenstein similarity

#https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=4160958

In [10]:
def  Levenstein(arr1, arr2):
    import numpy as np
    
    return np.count_nonzero(arr1 - arr2)
    

In [1]:
import numpy as np
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
np.count_nonzero(np.eye(9))

9

In [9]:
a = np.array([[0, 1, 7, 9],
              [3, 0, 2, 19]])
b= np.array([[7, 8, 7, 9],
              [3, 10, 20, 19]])
print(a-b)
print(type(a-b), (a-b).shape)

[[ -7  -7   0   0]
 [  0 -10 -18   0]]
<class 'numpy.ndarray'> (2, 4)


In [7]:
np.count_nonzero(a)

6

In [1]:
import numpy as np
idn= np.array([0,1,2,3,4, 99, 100,81,1863,2073, 2409,5438,6071])

x_min = np.zeros(idn.shape[0])
y_min= np.zeros(idn.shape[0])

x_max = np.zeros(idn.shape[0])
y_max = np.zeros(idn.shape[0])




for i in range (idn.shape[0]):
    
    x_min[i] = (idn[i]%100) * 256
    x_max[i] = ((idn[i] + 1) %100) * 256
    
    y_min[i]= int(idn[i]/100) * 256
    y_max[i]= (int(idn[i]/100) + 1) * 256
    
    print(idn[i], x_min[i],x_max[i],y_min[i],y_max[i])
    print("\n")

0 0.0 256.0 0.0 256.0


1 256.0 512.0 0.0 256.0


2 512.0 768.0 0.0 256.0


3 768.0 1024.0 0.0 256.0


4 1024.0 1280.0 0.0 256.0


99 25344.0 0.0 0.0 256.0


100 0.0 256.0 256.0 512.0


81 20736.0 20992.0 0.0 256.0


1863 16128.0 16384.0 4608.0 4864.0


2073 18688.0 18944.0 5120.0 5376.0


2409 2304.0 2560.0 6144.0 6400.0


5438 9728.0 9984.0 13824.0 14080.0


6071 18176.0 18432.0 15360.0 15616.0




In [ ]:
filename_lattitude = "C:\\12months\\lat_geotiff.tif"
filename_longitude= "C:\\12months\\lon_geotiff.tif"

gtif = gdal.Open(filename_lattitude)
band=gtif.GetRasterBand(1)
lattitude = band.ReadAsArray()

gtif = gdal.Open(filename_longitude)
band=gtif.GetRasterBand(1)
longitude = band.ReadAsArray()

print(np.amax(array_hh))
print("hh" + str(array_hh.shape))
image_hh_list.append(array_hh)
    